# Generated by Django 4.2.8 on 2026-04-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('MaNCC', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TenNCC', models.CharField(max_length=255)),
                ('DChi_NCC', models.TextField()),
                ('SDT_NCC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=255)),
                ('DVT', models.CharField(max_length=50)),
                ('TrangThai', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('MaPhieu', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NgayNhap', models.DateField()),
                ('TongTien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('TrangThai', models.CharField(max_length=50)),
                ('MaNCC', models.ForeignKey(db_column='MaNCC', on_delete=django.db.models.deletion.CASCADE, to='KimLienTester.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='LoHang',
            fields=[
                ('MaLH', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('HSD', models.DateField()),
                ('SoLuong', models.IntegerField()),
                ('TrangThai', models.CharField(max_length=50)),
                ('MaSP', models.ForeignKey(db_column='MaSP', on_delete=django.db.models.deletion.CASCADE, to='KimLienTester.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuongNhap', models.IntegerField()),
                ('DonGiaNhap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ThanhTien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('MaLH', models.ForeignKey(db_column='MaLH', on_delete=django.db.models.deletion.CASCADE, to='KimLienTester.lohang')),
                ('MaPhieu', models.ForeignKey(db_column='MaPhieu', on_delete=django.db.models.deletion.CASCADE, to='KimLienTester.phieunhap')),
            ],
        ),
    ]
