# Generated by Django 4.2.8 on 2026-04-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KimLienTester', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chitietnhap',
            options={'verbose_name': 'Chi tiết nhập', 'verbose_name_plural': 'Chi tiết nhập'},
        ),
        migrations.AlterModelOptions(
            name='lohang',
            options={'verbose_name': 'Lô hàng', 'verbose_name_plural': 'Lô hàng'},
        ),
        migrations.AlterModelOptions(
            name='nhacungcap',
            options={'verbose_name': 'Nhà cung cấp', 'verbose_name_plural': 'Nhà cung cấp'},
        ),
        migrations.AlterModelOptions(
            name='phieunhap',
            options={'verbose_name': 'Phiếu nhập', 'verbose_name_plural': 'Phiếu nhập'},
        ),
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
    ]
