# Generated by Django 4.2.8 on 2026-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KimLienTester', '0002_alter_chitietnhap_options_alter_lohang_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lohang',
            name='SoLuong',
        ),
        migrations.AddField(
            model_name='nhacungcap',
            name='TrangThai',
            field=models.CharField(default='Hợp tác', max_length=20),
        ),
    ]
